' Developer Express Code Central Example:
' Three discontinuous custom time scales for the Timeline view
' 
' This example illustrates three discontinuous custom scales for the Timeline view
' which are properly aligned. The first scale is a day scale which skips Saturdays
' and Sundays. The second scale is an hour scale which contains only working hours
' from 6 to 21. The third scale with increments of 30 minutes displays hours from
' 6 to 21, like the second scale.
' Note the paint correction code which amends the
' color for the columns situated by the scale discontinuities.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E1480

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")> _
    Friend NotInheritable Partial Class Settings
        Inherits System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

        Public Shared ReadOnly Property [Default]() As Settings
            Get
                Return defaultInstance
            End Get
        End Property
    End Class
End Namespace
