// Developer Express Code Central Example:
// Three discontinuous custom time scales for the Timeline view
// 
// This example illustrates three discontinuous custom scales for the Timeline view
// which are properly aligned. The first scale is a day scale which skips Saturdays
// and Sundays. The second scale is an hour scale which contains only working hours
// from 6 to 21. The third scale with increments of 30 minutes displays hours from
// 6 to 21, like the second scale.
// Note the paint correction code which amends the
// color for the columns situated by the scale discontinuities.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E1480

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimelineTimeScales.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
